name: Deploy React App
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build page
      run: npm run build
    - run: |
        git config user.name e2517
        git config user.email ${{ secrets.EMAIL_GMAIL }}
        git add .
        git commit -m "[update]"
        git push origin master
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./build
